### PR TITLE
Updated API to 3.0 and brought back F1Live (formerly Pit Lane Channel)

### PR DESCRIPTION
**Pull request by LoVega1337**
- Updated API to 3.0
- Added back F1Live (formerly Pit Lane Channel)

WIF and International might be the same channel, I've added both, please verify.

**Please test before merging.**

### CODE REVIEW

**Comment by leonardoxh** [comment]
My first question is, is this really a 3.0 api ?

It just seems changes in the current 2.0 apis, as the URL's and everything else remains the same.

**Comment by LoVega1337** [comment]
Building an APK through GitHub Actions threw me an error because I forgot to add the new channels to the card selection. I have added them now and an APK got built successfully. Version to test if above is working: [apk.zip](https://github.com/leonardoxh/race-control-tv/files/8455770/apk.zip)
The APK is inside that ZIP that GitHub Actions built. If it won't install you might need to uninstall your current installation and then install this one since I haven't changed the version number.

**Comment by leonardoxh** [comment]
I tried out, and I see a few problems:
1. The main broadcast and International seem the same thing
2. The international channel never load

My actual suggestion is to remove the international channel and keep only the `Main Broadcast` and `F1 Live`

**Comment by leonardoxh** [comment]
I tried out, and I see a few problems:
1. The main broadcast and International seem the same thing
2. The international channel never load

My actual suggestion is to remove the international channel and keep only the `Main Broadcast` and `F1 Live`

**Comment by leonardoxh** [comment]
Do you want to take care of this @LoVega1337 or shall I take over? 

Because this change is really good to resurrect these parts

**Comment by leonardoxh** [comment]
Do you want to take care of this @LoVega1337 or shall I take over? 

Because this change is really good to resurrect these parts

**Comment by LoVega1337** [comment]
@leonardoxh Ah yeah I figured it might be the same thing, odd that it doesn't load though.

But yes I'll remove the International part then and just keep the F1 Live and API change. Both of the problems you mentioned will be resolved with this anyway 😁

**Comment by LoVega1337** [comment]
@leonardoxh Deleted the technical part of the International channel since it didn't work, although I have renamed "Main Broadcast" to "International" in the UI to make it more aligned with the official F1 channels.

**Comment by leonardoxh** [comment]
@LoVega1337 I do see another issue now that I still have 3 channels, `International` `F1 LIVE` and `INTERNATIONAL` this last one never loads...

**Comment by leonardoxh** [comment]
I think the `International` (the one I create by hand) is no longer required with this `INTERNATIONAL` channel that comes up now, there is a problem with the way URL is created...

It is resolved to this:
https://f1tv.formula1.com/1.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/PLAY?contentId=1000005122&channelId=1000005122

I think for these channels we need to start use the `playbackUrl`

**Comment by leonardoxh** [comment]
I will merge this and solve this issue

**Pull request merged**
